import {
  BadgeDollarSign,
  BarChart3,
  Boxes,
  BriefcaseBusiness,
  Building2,
  ClipboardCheck,
  FileText,
  Handshake,
  HardHat,
  Landmark,
  MapPinned,
  Network,
  PackageSearch,
  Route,
  ShieldCheck,
  Store,
  Truck,
  type LucideIcon,
} from "lucide-react";

export type PersonaKey = "client" | "contractor" | "developer" | "architect" | "engineer" | "quantity_surveyor" | "project_manager" | "supplier" | "manufacturer" | "logistics" | "financier" | "institution" | "administrator" | "operations" | "custom";
export type NavItem = { label: string; path: string; icon: LucideIcon; readiness: "live" | "guided" | "planned" };
export type PersonaDefinition = { key: PersonaKey; label: string; shortLabel: string; description: string; icon: LucideIcon; accent: string; dashboardTitle: string; navigation: NavItem[]; nextActions: string[] };

const governed = { label: "Registry & governance", path: "/catalogue", icon: Network, readiness: "live" as const };
const ai = { label: "AI workspace", path: "/agents", icon: PackageSearch, readiness: "live" as const };
const approvals = { label: "Approvals", path: "/approvals", icon: ClipboardCheck, readiness: "guided" as const };

export const PERSONAS: Record<PersonaKey, PersonaDefinition> = {
  client: { key: "client", label: "Client / Homeowner", shortLabel: "Client", description: "Project visibility, budget decisions, approvals, and handover readiness.", icon: Building2, accent: "bg-violet-600", dashboardTitle: "Your project, decisions, and milestones", navigation: [{ label: "My projects", path: "/projects", icon: BriefcaseBusiness, readiness: "guided" }, { label: "Budget & payments", path: "/finance", icon: BadgeDollarSign, readiness: "planned" }, { label: "Materials", path: "/procurement", icon: PackageSearch, readiness: "live" }, { label: "Documents", path: "/files", icon: FileText, readiness: "live" }, approvals, ai], nextActions: ["Review decision-ready approvals", "Track procurement evidence", "Confirm project milestones"] },
  contractor: { key: "contractor", label: "Contractor", shortLabel: "Contractor", description: "Plan projects, coordinate sites, procure materials, and control project delivery.", icon: HardHat, accent: "bg-teal-700", dashboardTitle: "From BOQ to site delivery", navigation: [{ label: "Projects", path: "/projects", icon: BriefcaseBusiness, readiness: "live" }, { label: "Site operations", path: "/site", icon: MapPinned, readiness: "guided" }, { label: "BOQ & estimating", path: "/boq", icon: ClipboardCheck, readiness: "guided" }, { label: "Procurement", path: "/procurement", icon: PackageSearch, readiness: "live" }, { label: "RFQs & quotes", path: "/rfqs", icon: Handshake, readiness: "live" }, { label: "Deliveries", path: "/deliveries", icon: Truck, readiness: "guided" }, { label: "Documents", path: "/files", icon: FileText, readiness: "live" }, ai], nextActions: ["Map material requirements to canonical products", "Compare eligible supplier offers", "Record site progress with evidence"] },
  developer: { key: "developer", label: "Developer", shortLabel: "Developer", description: "Portfolio health, cost exposure, procurement, risk, and approval control.", icon: Building2, accent: "bg-indigo-700", dashboardTitle: "Portfolio intelligence with project context", navigation: [{ label: "Portfolio", path: "/projects", icon: BriefcaseBusiness, readiness: "guided" }, { label: "Procurement", path: "/procurement", icon: PackageSearch, readiness: "live" }, { label: "Financials", path: "/finance", icon: BadgeDollarSign, readiness: "planned" }, { label: "Risks & approvals", path: "/approvals", icon: ShieldCheck, readiness: "guided" }, { label: "Documents", path: "/files", icon: FileText, readiness: "live" }, ai], nextActions: ["Review cross-project exceptions", "Approve controlled procurement actions", "Inspect evidence before cost decisions"] },
  architect: { key: "architect", label: "Architect", shortLabel: "Architect", description: "Design documents, specifications, revisions, and coordinated project decisions.", icon: FileText, accent: "bg-sky-700", dashboardTitle: "Design context, versions, and coordination", navigation: [{ label: "Projects", path: "/projects", icon: BriefcaseBusiness, readiness: "guided" }, { label: "Drawings", path: "/files", icon: FileText, readiness: "live" }, { label: "Specifications", path: "/catalogue", icon: Network, readiness: "live" }, { label: "RFIs & changes", path: "/approvals", icon: ClipboardCheck, readiness: "guided" }, ai], nextActions: ["Upload a controlled drawing revision", "Link specifications to products", "Review pending design approvals"] },
  engineer: { key: "engineer", label: "Engineer", shortLabel: "Engineer", description: "Technical documentation, inspections, quality, safety, and site evidence.", icon: ShieldCheck, accent: "bg-cyan-700", dashboardTitle: "Technical controls close to the work", navigation: [{ label: "Projects", path: "/projects", icon: BriefcaseBusiness, readiness: "guided" }, { label: "Inspections", path: "/site", icon: ClipboardCheck, readiness: "guided" }, { label: "Technical documents", path: "/files", icon: FileText, readiness: "live" }, { label: "Quality & safety", path: "/site", icon: ShieldCheck, readiness: "guided" }, ai], nextActions: ["Review controlled evidence", "Flag a technical exception", "Prepare an inspection record"] },
  quantity_surveyor: { key: "quantity_surveyor", label: "Quantity Surveyor", shortLabel: "QS", description: "BOQ, rates, estimating, procurement comparison, valuation, and change control.", icon: ClipboardCheck, accent: "bg-amber-700", dashboardTitle: "Cost intelligence anchored to the BOQ", navigation: [{ label: "BOQ & estimating", path: "/boq", icon: ClipboardCheck, readiness: "guided" }, { label: "Products & rates", path: "/catalogue", icon: Network, readiness: "live" }, { label: "Procurement", path: "/procurement", icon: PackageSearch, readiness: "live" }, { label: "Valuations", path: "/finance", icon: BadgeDollarSign, readiness: "planned" }, ai], nextActions: ["Map a rate to a canonical product", "Check comparable supplier offers", "Review cost evidence gaps"] },
  project_manager: { key: "project_manager", label: "Project Manager", shortLabel: "Project manager", description: "Exceptions, tasks, approvals, risk, progress, and cross-team workflow coordination.", icon: BriefcaseBusiness, accent: "bg-blue-700", dashboardTitle: "Manage exceptions before they become delays", navigation: [{ label: "Projects", path: "/projects", icon: BriefcaseBusiness, readiness: "guided" }, { label: "Tasks & approvals", path: "/approvals", icon: ClipboardCheck, readiness: "guided" }, { label: "Schedule & risks", path: "/site", icon: MapPinned, readiness: "guided" }, { label: "Procurement", path: "/procurement", icon: PackageSearch, readiness: "live" }, ai], nextActions: ["Review exceptions", "Route a blocked approval", "Check procurement readiness"] },
  supplier: { key: "supplier", label: "Supplier", shortLabel: "Supplier", description: "Sell governed catalogue offers, update stock and prices, respond to RFQs, and fulfil orders.", icon: Store, accent: "bg-emerald-700", dashboardTitle: "Sell from verified catalogue and stock", navigation: [{ label: "Master POS", path: "/pos", icon: Store, readiness: "guided" }, { label: "Catalogue & offers", path: "/offers", icon: Boxes, readiness: "live" }, { label: "Inventory", path: "/inventory", icon: Boxes, readiness: "guided" }, { label: "RFQs & quotations", path: "/rfqs", icon: Handshake, readiness: "live" }, { label: "Orders & delivery", path: "/deliveries", icon: Truck, readiness: "guided" }, { label: "Sales & invoices", path: "/finance", icon: BadgeDollarSign, readiness: "planned" }, { label: "Supplier matching", path: "/submissions", icon: Network, readiness: "live" }, ai], nextActions: ["Map a supplier product to the master catalogue", "Update evidence-backed availability", "Respond to an invited RFQ"] },
  manufacturer: { key: "manufacturer", label: "Manufacturer", shortLabel: "Manufacturer", description: "Manage official product information, controlled documents, distributors, and market demand.", icon: Boxes, accent: "bg-orange-700", dashboardTitle: "Authoritative product information, downstream context", navigation: [{ label: "Product master", path: "/catalogue", icon: Network, readiness: "live" }, { label: "Specifications", path: "/files", icon: FileText, readiness: "live" }, { label: "Pricing & availability", path: "/offers", icon: BadgeDollarSign, readiness: "live" }, { label: "Distribution", path: "/marketplace", icon: Handshake, readiness: "guided" }, { label: "Market intelligence", path: "/reports", icon: BarChart3, readiness: "guided" }, ai], nextActions: ["Review technical document evidence", "Maintain authoritative product attributes", "Inspect permitted product demand"] },
  logistics: { key: "logistics", label: "Logistics Provider", shortLabel: "Logistics", description: "Coordinate delivery requests, dispatch, route, proof of delivery, and performance.", icon: Truck, accent: "bg-rose-700", dashboardTitle: "Move materials with project-aware proof", navigation: [{ label: "Delivery board", path: "/deliveries", icon: Truck, readiness: "guided" }, { label: "Routes & locations", path: "/locations", icon: Route, readiness: "live" }, { label: "Proof of delivery", path: "/files", icon: FileText, readiness: "live" }, { label: "Earnings", path: "/finance", icon: BadgeDollarSign, readiness: "planned" }, ai], nextActions: ["Confirm route-ready deliveries", "Capture evidence of handover", "Escalate delivery exceptions"] },
  financier: { key: "financier", label: "Financier", shortLabel: "Financier", description: "Assess governed project evidence, procurement exposure, risk, financing, and disbursement controls.", icon: Landmark, accent: "bg-slate-800", dashboardTitle: "Evidence-led project finance oversight", navigation: [{ label: "Portfolio", path: "/projects", icon: BriefcaseBusiness, readiness: "guided" }, { label: "Financing", path: "/finance", icon: Landmark, readiness: "planned" }, { label: "Risk & approvals", path: "/approvals", icon: ShieldCheck, readiness: "guided" }, { label: "Project evidence", path: "/files", icon: FileText, readiness: "live" }, ai], nextActions: ["Review evidence completeness", "Inspect procurement exposure", "Route an approval for accountable review"] },
  institution: { key: "institution", label: "Government / Institutional Client", shortLabel: "Institution", description: "Govern project portfolios with procurement, compliance, audit, and controlled approval views.", icon: Landmark, accent: "bg-purple-800", dashboardTitle: "Public-interest oversight with traceability", navigation: [{ label: "Portfolio", path: "/projects", icon: BriefcaseBusiness, readiness: "guided" }, { label: "Procurement", path: "/procurement", icon: PackageSearch, readiness: "live" }, { label: "Audit & approvals", path: "/approvals", icon: ShieldCheck, readiness: "guided" }, { label: "Reports", path: "/reports", icon: BarChart3, readiness: "guided" }, ai], nextActions: ["Review approval controls", "Inspect audit evidence", "Review procurement comparability"] },
  administrator: { key: "administrator", label: "Wajenzi Administrator", shortLabel: "Administrator", description: "Run registry stewardship, data-quality control, marketplace oversight, and agent governance.", icon: ShieldCheck, accent: "bg-slate-950", dashboardTitle: "Network control with governed data quality", navigation: [{ label: "Registry control", path: "/catalogue", icon: Network, readiness: "live" }, { label: "Supplier review", path: "/submissions", icon: Handshake, readiness: "live" }, { label: "Data quality", path: "/quality", icon: ShieldCheck, readiness: "guided" }, { label: "Master POS", path: "/pos", icon: Store, readiness: "guided" }, { label: "Operations", path: "/operations", icon: BarChart3, readiness: "guided" }, ai], nextActions: ["Resolve canonicalization proposals", "Inspect agent proposals", "Review evidence and freshness gaps"] },
  operations: { key: "operations", label: "Wajenzi Operations", shortLabel: "Operations", description: "Coordinate onboarding, data stewardship, support, workflow health, and controlled interventions.", icon: BarChart3, accent: "bg-slate-700", dashboardTitle: "Operate the network without bypassing governance", navigation: [{ label: "Command center", path: "/", icon: BarChart3, readiness: "live" }, { label: "Onboarding", path: "/submissions", icon: Handshake, readiness: "live" }, { label: "Evidence vault", path: "/files", icon: FileText, readiness: "live" }, { label: "Data quality", path: "/quality", icon: ShieldCheck, readiness: "guided" }, ai], nextActions: ["Review onboarding queue", "Find governance exceptions", "Support a controlled workflow"] },
  custom: { key: "custom", label: "Custom organization role", shortLabel: "Custom role", description: "A permission-led view constructed from the organization’s approved role configuration.", icon: BriefcaseBusiness, accent: "bg-slate-600", dashboardTitle: "Your approved work context", navigation: [governed, { label: "Projects", path: "/projects", icon: BriefcaseBusiness, readiness: "guided" }, { label: "Documents", path: "/files", icon: FileText, readiness: "live" }, approvals, ai], nextActions: ["Review assigned work", "Use permission-approved actions", "Escalate an access need"] },
};

export const PERSONA_ORDER = Object.keys(PERSONAS) as PersonaKey[];

export function defaultPersonaForWorkspaceRole(role?: string | null): PersonaKey {
  if (role === "supplier") return "supplier";
  if (role === "contractor") return "contractor";
  if (role === "project_user") return "project_manager";
  if (role === "registry_steward") return "administrator";
  return "custom";
}
