export const workspaceSlugs = ["homeowner", "contractor", "developer", "architect", "engineer", "quantity-surveyor", "project-manager", "supplier", "manufacturer", "logistics", "financier", "institutional", "custom-role", "agent", "projects", "escrow", "finance", "insights", "admin", "operations", "onboarding"] as const;
export type WorkspaceSlug = (typeof workspaceSlugs)[number];

type WorkspaceSnapshot = {
  workspace: WorkspaceSlug;
  label: string;
  caption: string;
  metrics: Array<{ label: string; value: string; delta: string; tone: "amber" | "blue" | "green" | "red" }>;
  attention: Array<{ label: string; detail: string; tone: "success" | "warning" | "danger" | "info" }>;
};

type SnapshotContent = Omit<WorkspaceSnapshot, "workspace">;

const snapshots: Partial<Record<WorkspaceSlug, SnapshotContent>> = {
  homeowner: { label: "Homeowner Command Centre", caption: "Project progress, protected orders, and material decisions in one view.", metrics: [{ label: "Project budget", value: "KES 1.84M", delta: "6.4%", tone: "amber" }, { label: "Protected orders", value: "3", delta: "2 active", tone: "green" }, { label: "Materials sourced", value: "68%", delta: "12 pts", tone: "blue" }], attention: [{ label: "BOQ needs review", detail: "Mombasa Road Residence", tone: "warning" }, { label: "Delivery en route", detail: "Structural steel · ETA 14:20", tone: "info" }] },
  contractor: { label: "Contractor Operations", caption: "Coordinate procurement requests, material spend, supplier responses, and site deliveries.", metrics: [{ label: "Active projects", value: "7", delta: "2 new", tone: "blue" }, { label: "Open RFQs", value: "18", delta: "5 today", tone: "amber" }, { label: "Cost variance", value: "-1.8%", delta: "On plan", tone: "green" }], attention: [{ label: "RFQ response due", detail: "Finishes package · 4 suppliers", tone: "warning" }, { label: "Delivery scheduled", detail: "Athi River site · tomorrow", tone: "info" }] },
  supplier: { label: "Supplier Command Centre", caption: "Keep catalog availability, quotations, orders, and revenue intelligence in sync.", metrics: [{ label: "Revenue this month", value: "KES 864K", delta: "18.2%", tone: "green" }, { label: "Catalog health", value: "94%", delta: "3 gaps", tone: "amber" }, { label: "Pending RFQs", value: "12", delta: "4 urgent", tone: "blue" }], attention: [{ label: "Stock cover low", detail: "Cement 50kg · 3 days", tone: "warning" }, { label: "New quotation", detail: "Roofing package · KES 326K", tone: "info" }] },
  logistics: { label: "Logistics Control Tower", caption: "Assign drivers, monitor active site routes, and close proof-of-delivery loops.", metrics: [{ label: "Active routes", value: "14", delta: "3 on time", tone: "blue" }, { label: "On-time delivery", value: "96.8%", delta: "2.6 pts", tone: "green" }, { label: "Fleet utilisation", value: "82%", delta: "6 pts", tone: "amber" }], attention: [{ label: "Driver check-in", detail: "KCA 618B · Syokimau", tone: "info" }, { label: "Route exception", detail: "Westlands drop-off · 12 min delay", tone: "warning" }] },
  escrow: { label: "Escrow & Payments", caption: "Review protected transaction flows, settlement readiness, disputes, and KYC signals.", metrics: [{ label: "Funds in escrow", value: "KES 6.2M", delta: "12.4%", tone: "amber" }, { label: "Release queue", value: "24", delta: "8 today", tone: "blue" }, { label: "KYC clear", value: "98.6%", delta: "0.8 pts", tone: "green" }], attention: [{ label: "Release approval", detail: "WZ-2408-032 · KES 186K", tone: "warning" }, { label: "KYC review", detail: "Supplier application · 1 document", tone: "danger" }] },
  agent: { label: "AI Procurement Agent", caption: "Turn project requirements into comparable materials, RFQs, and reviewable procurement actions.", metrics: [{ label: "Procurement brief", value: "Ready", delta: "Context synced", tone: "green" }, { label: "Potential saving", value: "KES 48K", delta: "3 alternatives", tone: "amber" }, { label: "Supplier matches", value: "6", delta: "Verified", tone: "blue" }], attention: [{ label: "Recommended next step", detail: "Generate RFQ for concrete package", tone: "info" }, { label: "Review note", detail: "Confirm mix design with project engineer", tone: "warning" }] },
  admin: { label: "Wajenzi Administrator", caption: "Run the marketplace with a close view of trust, users, registry controls, and service health.", metrics: [{ label: "Marketplace GMV", value: "KES 28.4M", delta: "21.4%", tone: "green" }, { label: "Active buyers", value: "1,248", delta: "14.2%", tone: "blue" }, { label: "Verified suppliers", value: "186", delta: "9.6%", tone: "amber" }], attention: [{ label: "Verification queue", detail: "11 supplier applications", tone: "warning" }, { label: "System health", detail: "All core services operational", tone: "success" }] },
  projects: { label: "Project Intelligence", caption: "Understand material readiness, budget variance, milestones, and site delivery exposure.", metrics: [{ label: "Portfolio budget", value: "KES 14.7M", delta: "3.4%", tone: "amber" }, { label: "Material readiness", value: "76%", delta: "8 pts", tone: "green" }, { label: "At-risk milestones", value: "2", delta: "Needs review", tone: "red" }], attention: [{ label: "Cost risk", detail: "Finishes package exceeds baseline", tone: "warning" }, { label: "Milestone ready", detail: "Foundation materials complete", tone: "success" }] },
  insights: { label: "Marketplace Intelligence", caption: "Track supply coverage, category demand, catalog quality, and commercial opportunity.", metrics: [{ label: "Demand signal", value: "+24%", delta: "Cement & steel", tone: "amber" }, { label: "Catalog coverage", value: "89%", delta: "6 counties", tone: "blue" }, { label: "Price stability", value: "92%", delta: "Last 30 days", tone: "green" }], attention: [{ label: "Category gap", detail: "Sanitaryware · Kiambu", tone: "warning" }, { label: "Growth signal", detail: "Finishes demand increasing", tone: "info" }] },
  finance: { label: "Finance & Risk", caption: "Monitor settlement exposure, KYC signals, protected transactions, and financial exceptions.", metrics: [{ label: "Settlement exposure", value: "KES 6.2M", delta: "12.4%", tone: "amber" }, { label: "KYC in review", value: "6", delta: "2 today", tone: "blue" }, { label: "Cases within SLA", value: "94%", delta: "4.2 pts", tone: "green" }], attention: [{ label: "Supplier KYC review", detail: "Business registration needs matching", tone: "warning" }, { label: "Settlement exception", detail: "Mobile money confirmation pending", tone: "danger" }] },
  onboarding: { label: "Supplier Onboarding", caption: "Guide hardware stores, manufacturers, and distributors through trusted marketplace verification.", metrics: [{ label: "Applications", value: "19", delta: "6 this week", tone: "blue" }, { label: "Verified", value: "8", delta: "42% conversion", tone: "green" }, { label: "Review needed", value: "5", delta: "Documents", tone: "amber" }], attention: [{ label: "Compliance required", detail: "Business registration document", tone: "warning" }, { label: "Score ready", detail: "Kiambu Building Supplies · 82/100", tone: "success" }] },
};

const roleLabels: Partial<Record<WorkspaceSlug, string>> = { developer: "Developer workspace", architect: "Architect workspace", engineer: "Engineer workspace", "quantity-surveyor": "Quantity surveyor workspace", "project-manager": "Project manager workspace", manufacturer: "Manufacturer workspace", financier: "Financier workspace", institutional: "Institutional client workspace", "custom-role": "Custom organization workspace", operations: "Wajenzi operations workspace" };

export function getWorkspaceSnapshot(workspace: WorkspaceSlug): WorkspaceSnapshot {
  const fallback: SnapshotContent = { label: roleLabels[workspace] ?? "Wajenzi.AI workspace", caption: "Manage the work, approvals, documents, project controls, and traceable next actions for your active role.", metrics: [{ label: "Open work", value: "12", delta: "Role queue", tone: "blue" }, { label: "Approvals", value: "4", delta: "Needs review", tone: "amber" }, { label: "Control status", value: "Ready", delta: "Traceable", tone: "green" }], attention: [{ label: "New action", detail: "Review the role work queue", tone: "info" }, { label: "Decision review", detail: "Confirm responsible approver", tone: "warning" }] };
  return { workspace, ...(snapshots[workspace] ?? fallback) };
}
