import { EmptyState, StatusPill, WajenziId, WorkspaceFrame } from "@/components/WorkspaceFrame";
import { trpc } from "@/lib/trpc";
import { Bot, CheckCircle2, ChevronRight, ClipboardCheck, FileCheck2, ShieldAlert } from "lucide-react";
import { Link } from "wouter";

const futureQueues = [
  ["RFQs and quotations", "Supplier response, commercial comparison, selection, and next purchase-order authorization."],
  ["Purchase orders and deliveries", "Order release, dispatch, receipt, inspection, and proof-of-delivery evidence."],
  ["Payments and finance", "Invoice review, eTIMS/M-PESA or banking integration, disbursement, and reconciliation."],
  ["Documents and changes", "Drawing issue, BOQ change, variation, technical review, and project milestone decision."],
];

export default function Approvals() {
  const dashboard = trpc.registry.dashboard.useQuery(undefined, { retry: false });
  const history = trpc.agents.history.useQuery(undefined, { retry: false });
  const agentProposals = history.data?.flatMap(run => run.proposals.map(proposal => ({ ...proposal, runWajenziId: run.wajenziId, agentKey: run.agentKey }))) || [];
  const pendingAgentProposals = agentProposals.filter(proposal => proposal.status === "pending_approval");
  return <WorkspaceFrame eyebrow="Accountable decision making" title="Approval center" description="Review what is actually awaiting an authorized decision. Every active decision retains a canonical or agent-run reference and produces a governed event; unavailable workflow types remain clearly marked until their backend services exist." action={<Link href="/agents" className="rounded-xl bg-teal-300 px-4 py-2.5 text-sm font-bold text-teal-950 transition hover:bg-teal-200">Open AI proposals</Link>}>
    <section className="grid gap-4 sm:grid-cols-3"><div className="data-card rounded-2xl p-5"><p className="text-[11px] font-bold uppercase tracking-[0.14em] text-slate-500">Canonical review</p><p className="mt-4 font-display text-3xl text-slate-900">{dashboard.data?.reviewQueue.length || 0}</p><p className="mt-1 text-xs leading-5 text-slate-500">Supplier product submissions needing stewardship</p></div><div className="data-card rounded-2xl p-5"><p className="text-[11px] font-bold uppercase tracking-[0.14em] text-slate-500">AI proposals</p><p className="mt-4 font-display text-3xl text-slate-900">{pendingAgentProposals.length}</p><p className="mt-1 text-xs leading-5 text-slate-500">Structured, source-bounded recommendations awaiting review</p></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><p className="text-[11px] font-bold uppercase tracking-[0.14em] text-amber-800">Controlled scope</p><p className="mt-4 font-display text-xl text-amber-950">No payment or PO authority yet</p><p className="mt-2 text-xs leading-5 text-amber-900">Financial and procurement approvals will appear only after their lifecycle services are governed and enabled.</p></div></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-2"><div className="data-card rounded-2xl"><div className="flex items-center justify-between border-b soft-divider px-5 py-4"><div><p className="text-[11px] font-bold uppercase tracking-[0.14em] text-slate-500">Live queue</p><h2 className="mt-1 font-display text-xl text-slate-900">Supplier canonicalization</h2></div><ShieldAlert className="h-5 w-5 text-amber-700" /></div>{dashboard.isLoading ? <p className="p-6 text-sm text-slate-500">Loading governed review queue…</p> : dashboard.data?.reviewQueue.length ? <div className="divide-y soft-divider">{dashboard.data.reviewQueue.map(item => <div key={item.id} className="flex items-center justify-between gap-4 px-5 py-4"><div className="min-w-0"><p className="truncate text-sm font-medium text-slate-800">{item.submittedName}</p><p className="mt-1"><WajenziId value={item.wajenziId} /></p></div><div className="flex items-center gap-3"><StatusPill value={item.status} /><Link href="/submissions" className="rounded-lg border border-slate-200 bg-white p-2 text-slate-600 transition hover:border-teal-300 hover:text-teal-800" aria-label="Review supplier submission"><ChevronRight className="h-4 w-4" /></Link></div></div>)}</div> : <EmptyState title="No canonicalization decision is waiting" detail="New supplier submissions appear here when their existing match is uncertain or a new canonical identity requires a steward." />}</div><div className="data-card rounded-2xl"><div className="flex items-center justify-between border-b soft-divider px-5 py-4"><div><p className="text-[11px] font-bold uppercase tracking-[0.14em] text-slate-500">Live queue</p><h2 className="mt-1 font-display text-xl text-slate-900">AI agent proposals</h2></div><Bot className="h-5 w-5 text-indigo-700" /></div>{history.isLoading ? <p className="p-6 text-sm text-slate-500">Loading agent proposals…</p> : pendingAgentProposals.length ? <div className="divide-y soft-divider">{pendingAgentProposals.map(proposal => <div key={proposal.id} className="flex items-center justify-between gap-4 px-5 py-4"><div className="min-w-0"><p className="text-sm font-medium capitalize text-slate-800">{proposal.proposalType.replaceAll("_", " ")}</p><p className="mt-1"><WajenziId value={proposal.wajenziId} /></p><p className="mt-1 text-[11px] text-slate-500">From {proposal.agentKey.replaceAll("_", " ")} · run <WajenziId value={proposal.runWajenziId} /></p></div><Link href="/agents" className="rounded-lg border border-slate-200 bg-white p-2 text-slate-600 transition hover:border-teal-300 hover:text-teal-800" aria-label="Review agent proposal"><ChevronRight className="h-4 w-4" /></Link></div>)}</div> : <EmptyState title="No AI proposal awaits a decision" detail="Agents produce a proposal only when their bounded analysis identifies recommendations, missing evidence, or permitted candidate records." />}</div></section>
    <section className="mt-6 data-card rounded-2xl"><div className="border-b soft-divider px-5 py-4"><p className="text-[11px] font-bold uppercase tracking-[0.14em] text-slate-500">Future governed queues</p><h2 className="mt-1 font-display text-xl text-slate-900">Workflow approvals by lifecycle stage</h2></div><div className="grid divide-y soft-divider md:grid-cols-2 md:divide-x md:divide-y-0">{futureQueues.map(([title, detail]) => <div key={title} className="p-5"><div className="flex items-center gap-2"><FileCheck2 className="h-4 w-4 text-slate-500" /><p className="font-medium text-slate-800">{title}</p><span className="ml-auto text-[10px] font-bold uppercase tracking-wide text-slate-400">Planned</span></div><p className="mt-2 text-sm leading-6 text-slate-600">{detail}</p></div>)}</div><div className="border-t soft-divider bg-teal-50/60 px-5 py-4 text-xs leading-5 text-teal-950"><CheckCircle2 className="mr-1.5 inline h-3.5 w-3.5 text-teal-700" />Approval is never a substitute for backend authorization. Decision types activate only when their records, evidence, permissions, and audit event contracts are in place.</div></section>
  </WorkspaceFrame>;
}
