import { EmptyState, StatusPill, WajenziId, WorkspaceFrame } from "@/components/WorkspaceFrame";
import { trpc } from "@/lib/trpc";
import { Filter, Search } from "lucide-react";
import { useState } from "react";

export default function Catalogue() {
  const [search, setSearch] = useState("cement");
  const catalogue = trpc.registry.catalogue.useQuery({ search }, { retry: false });
  return <WorkspaceFrame eyebrow="Canonical identity layer" title="Master product catalogue" description="The canonical catalogue is a governed identity system—not a supplier price list. Supplier listings attach to this layer only after matching or steward approval." action={<div className="rounded-xl border border-white/15 bg-white/10 px-3 py-2 font-mono-data text-[11px] text-teal-100">13,180 source rows validated</div>}>
    <div className="data-card rounded-2xl"><div className="flex flex-col gap-4 border-b soft-divider p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted-foreground">Search canonical records</p><p className="mt-1 text-sm text-slate-700">Immutable WAJENZI IDs are issued per canonical product or variant.</p></div><label className="flex w-full max-w-md items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2.5 shadow-sm sm:w-80"><Search className="h-4 w-4 text-teal-700" /><input value={search} onChange={event => setSearch(event.target.value)} className="w-full bg-transparent text-sm outline-none" placeholder="Search products" /></label></div>
      {catalogue.isLoading ? <div className="p-8 text-sm text-muted-foreground">Loading canonical records…</div> : catalogue.error ? <div className="p-8 text-sm text-rose-700">{catalogue.error.message}</div> : catalogue.data?.length ? <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-[0.13em] text-slate-500"><tr><th className="px-5 py-3 font-bold">Canonical product</th><th className="px-5 py-3 font-bold">WAJENZI ID</th><th className="px-5 py-3 font-bold">Identity data</th><th className="px-5 py-3 font-bold">Status</th></tr></thead><tbody className="divide-y soft-divider">{catalogue.data.map(row => <tr key={row.id} className="hover:bg-teal-50/30"><td className="px-5 py-4"><p className="font-medium text-slate-800">{row.canonicalName}</p><p className="mt-1 text-xs text-muted-foreground">{row.detail?.brand || "Brand pending"} · {row.detail?.packSize || "Pack detail pending"}</p></td><td className="px-5 py-4"><WajenziId value={row.wajenziId} /></td><td className="px-5 py-4 text-xs text-slate-600"><span className="capitalize">{row.detail?.productKind}</span> · {row.detail?.unitOfMeasure || "unit pending"}<br /><span className="text-muted-foreground">Source: {row.sourceSystem || "—"}</span></td><td className="px-5 py-4"><StatusPill value={row.lifecycleStatus} /></td></tr>)}</tbody></table></div> : <EmptyState title="No canonical records found" detail="Try another product name or load an approved catalogue import batch." />}
    </div>
    <div className="mt-5 flex gap-3 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs leading-5 text-amber-900"><Filter className="h-4 w-4 shrink-0" /> Supplier commercial fields—price, stock, lead time, and terms—are intentionally not displayed here. They exist as separate offer observations in the procurement workspace.</div>
  </WorkspaceFrame>;
}
