import { EmptyState, WorkspaceFrame } from "@/components/WorkspaceFrame";
import { usePersona } from "@/components/DashboardLayout";
import { BellRing, Link2, ListChecks, LockKeyhole, MessageSquareText, Plus, ShieldCheck } from "lucide-react";
import { toast } from "sonner";

export default function CollaborationHub({ kind }: { kind: "tasks" | "messages" }) {
  const copy = kind === "tasks" ? { eyebrow: "Shared work coordination", title: "Tasks", description: "Assignments, due dates, approvals, and escalation will be connected to the underlying project, work item, document, or procurement entity rather than managed as isolated reminders.", action: "Create task", icon: ListChecks, emptyTitle: "No governed tasks yet", emptyDetail: "Task creation activates when the task, assignment, notification, and project-permission services are introduced.", links: ["Project", "WBS / BOQ item", "RFQ / quotation", "Delivery", "Issue / risk", "Approval"] } : { eyebrow: "Entity-linked communication", title: "Messages", description: "Project, supplier, design, procurement, and delivery communication will be attached to governed records so decisions and evidence remain recoverable as part of the operational history.", action: "New message", icon: MessageSquareText, emptyTitle: "No governed messages yet", emptyDetail: "Messages activate when their secure conversation, participant, entity-link, notification, and retention services are introduced.", links: ["Project", "Product", "Supplier", "BOQ item", "RFQ / quotation", "Purchase order"] };
  const Icon = copy.icon;
  return <WorkspaceFrame eyebrow={copy.eyebrow} title={copy.title} description={copy.description} action={<button onClick={() => toast.info(`${copy.action} requires its governed backend record, permission, and event service before it can be activated.`)} className="rounded-xl bg-teal-300 px-4 py-2.5 text-sm font-bold text-teal-950 transition hover:bg-teal-200 active:scale-[0.97]">{copy.action}</button>}><CollaborationBody copy={copy} Icon={Icon} /></WorkspaceFrame>;
}

function CollaborationBody({ copy, Icon }: { copy: { action: string; emptyTitle: string; emptyDetail: string; links: string[] }; Icon: typeof ListChecks }) {
  const { persona, workspaceRole, workspaceName, activeProjectEntityId } = usePersona();
  const canAccessCollaboration = ["registry_steward", "supplier", "contractor", "project_user"].includes(workspaceRole || "");
  if (!canAccessCollaboration) return <section className="rounded-2xl border border-amber-200 bg-amber-50 p-7 text-center"><LockKeyhole className="mx-auto h-6 w-6 text-amber-700" /><p className="mt-3 text-[11px] font-bold uppercase tracking-[0.14em] text-amber-800">Access required</p><h2 className="mt-2 font-display text-2xl text-amber-950">This collaboration workspace is not authorized for your role</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-amber-900">Your current workspace authority is <strong>{workspaceRole?.replaceAll("_", " ") || "not available"}</strong>. Ask an authorized administrator to assign the relevant project and collaboration permissions before using {copy.action.toLowerCase()} workflows.</p></section>;
  return <><section className="grid gap-6 xl:grid-cols-[1.15fr_0.85fr]"><div className="data-card rounded-2xl"><div className="flex items-center gap-3 border-b soft-divider px-5 py-4"><span className="rounded-xl bg-teal-50 p-2 text-teal-700"><Icon className="h-5 w-5" /></span><div><p className="text-[11px] font-bold uppercase tracking-[0.14em] text-slate-500">Authorized work context</p><h2 className="font-display text-xl text-slate-900">{workspaceName || "Workspace"}</h2></div></div><EmptyState title={copy.emptyTitle} detail={copy.emptyDetail} /></div><div className="rounded-2xl border border-teal-900/10 bg-[#20323a] p-6 text-stone-100"><LockKeyhole className="h-5 w-5 text-teal-200" /><p className="mt-4 text-[11px] font-bold uppercase tracking-[0.14em] text-teal-200">Permission-aware rollout</p><p className="mt-2 font-display text-2xl">No unseen access through collaboration.</p><p className="mt-3 text-sm leading-6 text-stone-300">The current {persona.replaceAll("_", " ")} view is limited to <strong>{workspaceRole?.replaceAll("_", " ") || "workspace authority"}</strong>. New {copy.action.toLowerCase()} actions will be evaluated by organization, project, entity, and action permission before they are committed.</p><p className="mt-4 rounded-xl border border-white/15 bg-white/5 p-3 text-xs text-teal-50">Selected project context: {activeProjectEntityId ? "authorized project selected" : "all authorized projects"}</p></div></section><section className="data-card mt-6 rounded-2xl"><div className="border-b soft-divider px-5 py-4"><p className="text-[11px] font-bold uppercase tracking-[0.14em] text-slate-500">Required entity links</p><h2 className="mt-1 font-display text-xl text-slate-900">Collaboration remains part of the project record</h2></div><div className="grid gap-px bg-slate-200 md:grid-cols-3">{copy.links.map(link => <div key={link} className="bg-white p-5"><Link2 className="h-4 w-4 text-teal-700" /><p className="mt-3 font-medium text-slate-800">{link}</p><p className="mt-1 text-xs leading-5 text-slate-500">Conversation, task, decision, and related evidence will retain this entity context.</p></div>)}</div><div className="flex items-center gap-2 border-t soft-divider bg-teal-50/60 px-5 py-4 text-xs leading-5 text-teal-950"><ShieldCheck className="h-4 w-4 shrink-0 text-teal-700" />When activated, each creation, update, assignment, decision, and notification event will remain auditable. No placeholder activity has been generated.</div></section></>;
}
