import { EmptyState, StatusPill, WajenziId, WorkspaceFrame } from "@/components/WorkspaceFrame";
import { trpc } from "@/lib/trpc";
import { PERSONAS, type PersonaKey } from "@/lib/personas";
import { ArrowRight, CheckCircle2, CircleDashed, FileText, Layers3, LockKeyhole, MapPinned, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { Link } from "wouter";

type ModuleKey = "projects" | "site" | "boq" | "rfqs" | "deliveries" | "finance" | "approvals" | "pos" | "inventory" | "reports" | "quality" | "operations";

const MODULES: Record<ModuleKey, { eyebrow: string; title: string; description: string; action: string; actionDetail: string; phases: string[]; related: Array<{ label: string; href: string; live: boolean }> }> = {
  projects: { eyebrow: "Project context", title: "Project workspace", description: "Move from a governed project record to its site, documents, procurement, evidence, and lifecycle actions without duplicating project identity.", action: "Open project setup", actionDetail: "Governed project and optional initial-site creation are active for authorized project roles. Subsequent BOQ, WBS, progress, and closeout services remain separately controlled.", phases: ["Project brief & organization", "Site & location", "Drawings & BOQ", "Procurement plan", "Delivery & progress", "Handover & archive"], related: [{ label: "Locations", href: "/locations", live: true }, { label: "Procurement", href: "/procurement", live: true }, { label: "Documents", href: "/files", live: true }] },
  site: { eyebrow: "Site operations", title: "Field control workspace", description: "A mobile-first field workflow for daily reporting, quality, safety, progress, evidence, and location-aware coordination.", action: "Record site activity", actionDetail: "Site diary, inspection, attendance, and progress records require their dedicated operational data model before they can be committed.", phases: ["Daily diary", "Labour & equipment", "Material receipt", "Quality & safety", "Progress & issues", "Evidence & event"], related: [{ label: "Project locations", href: "/locations", live: true }, { label: "Evidence vault", href: "/files", live: true }, { label: "AI workspace", href: "/agents", live: true }] },
  boq: { eyebrow: "Cost & planning", title: "BOQ and estimating", description: "Connect drawing-derived quantities, work breakdown, canonical products, rates, and procurement requirements under controlled approval.", action: "Create BOQ", actionDetail: "The canonical catalogue is available now; BOQ, WBS, estimating, and approved rate structures are the next backend data-model release.", phases: ["Drawings", "Quantity extraction", "BOQ", "WBS mapping", "Product mapping", "Estimate & approval"], related: [{ label: "Master catalogue", href: "/catalogue", live: true }, { label: "Supplier offers", href: "/offers", live: true }, { label: "Procurement", href: "/procurement", live: true }] },
  rfqs: { eyebrow: "Supplier network", title: "RFQs and quotations", description: "Guide project material requirements through supplier selection, controlled quotation responses, buyer review, and a pending-approval purchase-order handoff.", action: "Open RFQ board", actionDetail: "Project-bound RFQs, registered-supplier invitations, supplier quotation submission, buyer review, and pending-approval PO drafts are active. PO approval, issue, dispatch, receipt, and payment remain separate governed services.", phases: ["Requirement", "Supplier selection", "RFQ", "Quotation", "Buyer review", "Pending approval"], related: [{ label: "RFQ board", href: "/rfqs", live: true }, { label: "Comparable offers", href: "/procurement", live: true }, { label: "Supplier offers", href: "/offers", live: true }] },
  deliveries: { eyebrow: "Logistics workflow", title: "Deliveries and material handover", description: "Coordinate dispatch, routing, proof of delivery, material receipt, inspection, and evidence without breaking project traceability.", action: "Schedule delivery", actionDetail: "Delivery, driver, dispatch, proof-of-delivery, and inventory-receipt records need their dedicated lifecycle services before they can be scheduled here.", phases: ["Delivery request", "Carrier assignment", "Dispatch", "Transit", "Proof of delivery", "Receipt & inspection"], related: [{ label: "Locations map", href: "/locations", live: true }, { label: "Evidence vault", href: "/files", live: true }, { label: "Supplier offers", href: "/offers", live: true }] },
  finance: { eyebrow: "Finance controls", title: "Financial workspace", description: "Link approved commercial, project, delivery, and evidence records to invoicing, payment, tax, cash-flow, and financing workflows as services are activated.", action: "Create financial record", actionDetail: "Invoices, payments, M-PESA, eTIMS, and banking integrations must be backed by dedicated financial services; this interface does not fabricate balances or initiate payments.", phases: ["Commercial basis", "Invoice", "Approval", "Payment", "Tax/eTIMS", "Reconciliation & audit"], related: [{ label: "Supplier offers", href: "/offers", live: true }, { label: "Evidence vault", href: "/files", live: true }, { label: "Approvals", href: "/approvals", live: false }] },
  approvals: { eyebrow: "Accountable action", title: "Approval center", description: "A unified inbox for decisions across product matching, commercial verification, procurement, documents, changes, and finance—each controlled by backend authority.", action: "Review pending decisions", actionDetail: "Only active governed review queues are shown now. RFQ, PO, payment, and finance approvals appear when their backend workflows are activated.", phases: ["Request", "Evidence", "Review", "Decision", "Event", "Next workflow action"], related: [{ label: "Supplier matching", href: "/submissions", live: true }, { label: "AI proposals", href: "/agents", live: true }, { label: "Evidence vault", href: "/files", live: true }] },
  pos: { eyebrow: "Supplier sales", title: "Supplier POS and master POS", description: "Design the governed point-of-sale path from product lookup to tax, payment, receipt, inventory event, and authorized Master POS aggregation.", action: "Start sale", actionDetail: "No sale, refund, stock movement, payment, receipt, or tax transaction is created until POS and financial services are activated.", phases: ["Product lookup", "Customer & project", "Basket", "Tax & discount", "Payment", "Receipt & inventory event"], related: [{ label: "Catalogue & offers", href: "/offers", live: true }, { label: "Master catalogue", href: "/catalogue", live: true }, { label: "Financial workspace", href: "/finance", live: false }] },
  inventory: { eyebrow: "Supplier operations", title: "Inventory and warehouses", description: "Coordinate controlled stock-in, stock-out, transfer, reservation, counts, and replenishment across supplier facilities and canonical products.", action: "Record inventory movement", actionDetail: "Availability observations can be recorded now with evidence; inventory movement, reservation, warehouse, and reorder entities require their dedicated backend lifecycle service.", phases: ["Warehouse", "Stock event", "Reservation", "Availability", "Reorder", "Audit"], related: [{ label: "Offers & observations", href: "/offers", live: true }, { label: "Locations", href: "/locations", live: true }, { label: "Evidence vault", href: "/files", live: true }] },
  reports: { eyebrow: "Decision intelligence", title: "Reports and performance", description: "Define role-specific reports from one governed entity graph rather than copied spreadsheets or disconnected dashboards.", action: "Generate report", actionDetail: "Reporting exports require dedicated report queries and permissions. Existing registry, import, and audit summaries remain available in the command center.", phases: ["Select governed scope", "Validate data quality", "Choose metrics", "Generate", "Review", "Export with audit"], related: [{ label: "Command center", href: "/", live: true }, { label: "Data quality", href: "/quality", live: false }, { label: "AI workspace", href: "/agents", live: true }] },
  quality: { eyebrow: "Data stewardship", title: "Data quality center", description: "Review duplicate risk, missing identifiers, incomplete classifications, weak relationships, stale stock, and evidence gaps through accountable remediation.", action: "Run evidence-quality agent", actionDetail: "The active agent identifies gaps and prepares a proposal; it cannot silently correct a governed record.", phases: ["Detect", "Explain", "Recommend", "Human approval", "Correct", "Audit"], related: [{ label: "AI workspace", href: "/agents", live: true }, { label: "Master catalogue", href: "/catalogue", live: true }, { label: "Supplier matching", href: "/submissions", live: true }] },
  operations: { eyebrow: "Network operations", title: "Operations control", description: "Coordinate onboarding, steward queues, evidence readiness, workflow health, and accountable support operations across authorized workspaces.", action: "Open operational queue", actionDetail: "The active steward queues are available from Supplier matching and AI agents. Cross-network operational analytics require approved datasets and service modules.", phases: ["Onboard", "Validate", "Match", "Review", "Activate", "Monitor"], related: [{ label: "Supplier matching", href: "/submissions", live: true }, { label: "Agent proposals", href: "/agents", live: true }, { label: "Implementation", href: "/implementation", live: true }] },
};

function personaLabel(key: PersonaKey) { return PERSONAS[key].shortLabel; }

export default function GuidedWorkspace({ module }: { module: ModuleKey }) {
  const config = MODULES[module];
  const dashboard = trpc.registry.dashboard.useQuery(undefined, { retry: false });
  return <WorkspaceFrame eyebrow={config.eyebrow} title={config.title} description={config.description} action={<button onClick={() => toast.info(config.actionDetail)} className="rounded-xl bg-teal-300 px-4 py-2.5 text-sm font-bold text-teal-950 transition hover:bg-teal-200 active:scale-[0.97]">{config.action}</button>}>{({ persona, projects }) => <>
    <section className="grid gap-4 xl:grid-cols-[1.25fr_0.75fr]"><div className="data-card rounded-2xl p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-teal-800">{personaLabel(persona)} workflow</p><h2 className="mt-2 font-display text-2xl text-slate-900">Context → workflow → evidence → event</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">This workspace makes the next required stage explicit. A stage is only actionable when its governed backend service and your permission exist.</p></div><Layers3 className="h-6 w-6 text-teal-700" /></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{config.phases.map((phase, index) => <div key={phase} className={`rounded-xl border p-4 ${index === 0 ? "border-teal-300 bg-teal-50" : "border-slate-200 bg-slate-50/80"}`}><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-500">Stage {index + 1}</p><p className="mt-2 text-sm font-semibold text-slate-800">{phase}</p><p className="mt-2 text-xs text-slate-500">{index === 0 ? "Contextual starting point" : "Requires governed completion"}</p></div>)}</div></div><div className="rounded-2xl border border-teal-900/10 bg-[#20323a] p-6 text-stone-100"><LockKeyhole className="h-5 w-5 text-teal-200" /><p className="mt-4 text-[11px] font-bold uppercase tracking-[0.16em] text-teal-200">Authority first</p><h2 className="mt-2 font-display text-2xl">One interface, no invented access.</h2><p className="mt-3 text-sm leading-6 text-stone-300">This is the <strong>{personaLabel(persona)}</strong> view. Switching the visual role does not grant a new role: the server remains the authority for every record and action.</p><div className="mt-5 rounded-xl border border-white/10 bg-white/5 p-3 text-xs leading-5 text-teal-50">Current backend authority: <strong>{dashboard.data?.membership.workspaceRole?.replaceAll("_", " ") || "loading"}</strong></div></div></section>
    <section className="mt-6 grid gap-4 lg:grid-cols-3"><div className="data-card rounded-2xl lg:col-span-2"><div className="border-b soft-divider px-5 py-4"><p className="text-[11px] font-bold uppercase tracking-[0.14em] text-slate-500">Connected operational records</p><h2 className="mt-1 font-display text-xl text-slate-900">Available governed context</h2></div>{dashboard.isLoading ? <p className="p-6 text-sm text-slate-500">Loading workspace context…</p> : dashboard.data?.projects.length ? <div className="divide-y soft-divider">{dashboard.data.projects.map(project => <div className="flex flex-wrap items-center justify-between gap-3 px-5 py-4" key={project.entityId}><div><p className="font-medium text-slate-800">{project.canonicalName}</p><p className="mt-1"><WajenziId value={project.wajenziId} /></p></div><StatusPill value={project.status} /></div>)}</div> : <EmptyState title="No governed project available" detail="Create or join a project through an authorized project workflow before using project-specific stages." />}</div><div className="data-card rounded-2xl p-5"><p className="text-[11px] font-bold uppercase tracking-[0.14em] text-slate-500">Go to live records</p><div className="mt-4 space-y-2">{config.related.map(item => <Link key={item.href + item.label} href={item.href} className="flex items-center justify-between rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm font-medium text-slate-700 transition hover:border-teal-300 hover:text-teal-800"><span>{item.label}</span><span className={`text-[10px] font-bold uppercase tracking-wide ${item.live ? "text-teal-700" : "text-slate-400"}`}>{item.live ? "Live" : "Guided"}</span><ArrowRight className="h-3.5 w-3.5" /></Link>)}</div><p className="mt-5 text-xs leading-5 text-slate-500"><CheckCircle2 className="mr-1 inline h-3.5 w-3.5 text-teal-700" />Live modules query governed workspace data. Guided modules explain the next service boundary without manufacturing operational records.</p></div></section>
  </>}</WorkspaceFrame>;
}
