import { StatusPill, WajenziId, WorkspaceFrame } from "@/components/WorkspaceFrame";
import { trpc } from "@/lib/trpc";
import { PERSONAS } from "@/lib/personas";
import { Activity, ArrowUpRight, Boxes, CircleAlert, FileClock, MapPin, PackageCheck, ShieldAlert, Sparkles } from "lucide-react";
import { Link } from "wouter";

function Metric({ label, value, detail, icon: Icon, accent = "text-teal-700" }: { label: string; value: number; detail: string; icon: typeof Boxes; accent?: string }) {
  return <div className="data-card lift-on-hover rounded-2xl p-5"><div className="flex items-start justify-between"><p className="text-xs font-semibold uppercase tracking-[0.13em] text-muted-foreground">{label}</p><div className={`rounded-lg bg-slate-100 p-2 ${accent}`}><Icon className="h-4 w-4" /></div></div><p className="mt-6 font-display text-3xl text-slate-900">{value.toLocaleString()}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{detail}</p></div>;
}

export default function Home() {
  const dashboard = trpc.registry.dashboard.useQuery(undefined, { retry: false });
  const data = dashboard.data;
  return <WorkspaceFrame eyebrow="Role-aware operating environment" title="Construction work moves with context." description="wajenzi.ai brings project, product, supplier, location, evidence, and approval context into one governed operating flow. Your active persona controls the interface; backend permissions remain the authority." action={<Link href="/agents" className="inline-flex items-center gap-2 rounded-xl bg-teal-300 px-4 py-2.5 text-sm font-bold text-teal-950 transition hover:bg-teal-200 active:scale-[0.97]">Ask your AI workspace <Sparkles className="h-4 w-4" /></Link>}>{({ persona, workspaceRole, workspaceName, projects }) => {
    const definition = PERSONAS[persona];
    return <>
      <section className={`relative overflow-hidden rounded-2xl ${definition.accent} p-6 text-white shadow-lg shadow-slate-900/10`}><div className="absolute right-0 top-0 h-32 w-32 -translate-y-10 translate-x-10 rounded-full border border-white/25" /><div className="relative flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-white/75">{definition.label} command center</p><h2 className="mt-2 font-display text-3xl leading-tight">{definition.dashboardTitle}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/80">{definition.description}</p></div><div className="rounded-xl border border-white/15 bg-black/10 px-4 py-3 text-xs leading-5 text-white/90"><strong>Active authority</strong><br />{workspaceRole?.replaceAll("_", " ") || "Loading workspace role"}</div></div></section>
      {dashboard.isLoading ? <div className="data-card mt-6 rounded-2xl p-8 text-sm text-muted-foreground">Loading governed work context…</div> : dashboard.error ? <div className="mt-6 rounded-2xl border border-rose-200 bg-rose-50 p-6 text-sm text-rose-800">{dashboard.error.message}</div> : data ? <>
        <div className="mt-6 flex flex-wrap items-center gap-2 text-xs"><StatusPill value={workspaceRole} /><span className="text-muted-foreground">Organization workspace</span><WajenziId value={data.workspace.wajenziId} /><span className="ml-auto rounded-full bg-slate-100 px-3 py-1.5 font-medium text-slate-600">{workspaceName || data.workspace.name}</span></div>
        <section className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Master products" value={data.counts.masterProducts} detail="Canonical identity layer" icon={PackageCheck} /><Metric label="Active offers" value={data.counts.activeOffers} detail="Commercial data, not product identity" icon={Activity} accent="text-sky-700" /><Metric label="Review queue" value={data.counts.reviewRequired} detail="Approval-gated steward work" icon={ShieldAlert} accent="text-amber-700" /><Metric label="Projects" value={projects.length} detail="Visible in this workspace" icon={Boxes} accent="text-indigo-700" /><Metric label="Active sites" value={data.counts.activeSites} detail="Distance-ready location anchors" icon={MapPin} accent="text-rose-700" /></section>
        <section className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_0.85fr]"><div className="data-card rounded-2xl"><div className="flex items-center justify-between border-b soft-divider px-5 py-4"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted-foreground">Next actions</p><h2 className="mt-1 font-display text-xl text-slate-900">What needs attention now</h2></div><CircleAlert className="h-5 w-5 text-amber-700" /></div><div className="divide-y soft-divider">{definition.nextActions.map((action, index) => <div key={action} className="flex items-center justify-between gap-3 px-5 py-4"><div className="flex min-w-0 items-center gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-slate-100 text-xs font-bold text-slate-600">{index + 1}</span><p className="text-sm font-medium text-slate-800">{action}</p></div><Link href={index === 0 ? definition.navigation[0]?.path || "/" : index === 1 ? "/procurement" : "/agents"} className="shrink-0 text-xs font-bold text-teal-700 hover:text-teal-900">Open <ArrowUpRight className="inline h-3.5 w-3.5" /></Link></div>)}</div></div><div className="data-card rounded-2xl"><div className="border-b soft-divider px-5 py-4"><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted-foreground">Shared entity context</p><h2 className="mt-1 font-display text-xl text-slate-900">Projects you can access</h2></div>{projects.length ? <div className="divide-y soft-divider">{projects.slice(0, 4).map(project => <div key={project.entityId} className="px-5 py-4"><p className="font-medium text-slate-800">{project.canonicalName}</p><p className="mt-1"><WajenziId value={project.wajenziId} /></p></div>)}</div> : <p className="px-5 py-8 text-sm leading-6 text-muted-foreground">No approved project is available in this workspace yet. Project creation is the next controlled workflow module.</p>}</div></section>
        <section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Link href="/procurement" className="lift-on-hover rounded-2xl border border-teal-200 bg-teal-50/70 p-5 transition"><PackageCheck className="h-5 w-5 text-teal-700" /><p className="mt-4 font-display text-xl text-teal-950">Procure from governed offers</p><p className="mt-2 text-sm leading-6 text-teal-900/80">Compare only records with required product, place, price, stock, freshness, and evidence gates.</p><span className="mt-4 inline-block text-xs font-bold text-teal-800">Open procurement query →</span></Link><Link href="/submissions" className="lift-on-hover rounded-2xl border border-indigo-100 bg-indigo-50/60 p-5 transition"><ShieldAlert className="h-5 w-5 text-indigo-700" /><p className="mt-4 font-display text-xl text-indigo-950">Control supplier product intake</p><p className="mt-2 text-sm leading-6 text-indigo-900/80">Match supplier submissions to canonical products without a silent merge or duplicate identity.</p><span className="mt-4 inline-block text-xs font-bold text-indigo-800">Open supplier matching →</span></Link><Link href="/agents" className="lift-on-hover rounded-2xl border border-amber-200 bg-amber-50/70 p-5 transition"><Sparkles className="h-5 w-5 text-amber-700" /><p className="mt-4 font-display text-xl text-amber-950">Ask a governed agent</p><p className="mt-2 text-sm leading-6 text-amber-900/80">Run a structured, source-bounded analysis and route consequential recommendations for review.</p><span className="mt-4 inline-block text-xs font-bold text-amber-800">Open AI workspace →</span></Link></section>
        <section className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><div className="data-card rounded-2xl"><div className="flex items-center justify-between border-b soft-divider px-5 py-4"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted-foreground">Live governed queue</p><h2 className="mt-1 font-display text-xl text-slate-900">Supplier matching and approvals</h2></div><Link href="/submissions" className="text-xs font-bold text-teal-700 hover:text-teal-900">Open queue</Link></div><div className="divide-y soft-divider">{data.reviewQueue.length ? data.reviewQueue.map(item => <div key={item.id} className="flex items-center justify-between gap-4 px-5 py-4"><div className="min-w-0"><p className="truncate font-medium text-slate-800">{item.submittedName}</p><p className="mt-1"><WajenziId value={item.wajenziId} /></p></div><StatusPill value={item.status} /></div>) : <p className="px-5 py-10 text-sm text-muted-foreground">No supplier submission requires review.</p>}</div></div><div className="data-card rounded-2xl"><div className="border-b soft-divider px-5 py-4"><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted-foreground">Event trail</p><h2 className="mt-1 font-display text-xl text-slate-900">Recent governed activity</h2></div><div className="divide-y soft-divider">{data.audits.slice(0, 5).map(event => <div key={event.id} className="px-5 py-3.5"><div className="flex items-center justify-between gap-2"><p className="font-mono-data text-[11px] text-teal-800">{event.eventType}</p><span className="text-[11px] text-muted-foreground">{new Date(event.occurredAt).toLocaleDateString()}</span></div><p className="mt-1 text-xs leading-5 text-slate-600">{event.rationale}</p></div>)}<Link href="/implementation" className="flex items-center gap-2 px-5 py-4 text-xs font-bold text-teal-700 hover:text-teal-900"><FileClock className="h-3.5 w-3.5" />See current workflow boundaries</Link></div></div></section>
      </> : null}
    </>;
  }}</WorkspaceFrame>;
}
