import { WorkspaceFrame, StatusPill, WajenziId } from "@/components/WorkspaceFrame";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowUpRight, Boxes, FileClock, MapPin, PackageCheck, ShieldAlert } from "lucide-react";
import { Link } from "wouter";

function Metric({ label, value, detail, icon: Icon, accent = "text-teal-700" }: { label: string; value: number; detail: string; icon: typeof Boxes; accent?: string }) {
  return <div className="data-card lift-on-hover rounded-2xl p-5"><div className="flex items-start justify-between"><p className="text-xs font-semibold uppercase tracking-[0.13em] text-muted-foreground">{label}</p><div className={`rounded-lg bg-slate-100 p-2 ${accent}`}><Icon className="h-4 w-4" /></div></div><p className="mt-6 font-display text-3xl text-slate-900">{value.toLocaleString()}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{detail}</p></div>;
}

export default function Home() {
  const dashboard = trpc.registry.dashboard.useQuery(undefined, { retry: false });
  const data = dashboard.data;
  return <WorkspaceFrame eyebrow="Governed registry workspace" title="Trusted construction data, ready to work." description="Manage the canonical product layer separately from supplier commercial facts, keep every change traceable, and move procurement decisions from searchable records to defensible evidence." action={<Link href="/procurement" className="inline-flex items-center gap-2 rounded-xl bg-teal-300 px-4 py-2.5 text-sm font-bold text-teal-950 transition hover:bg-teal-200 active:scale-[0.97]">Run procurement query <ArrowUpRight className="h-4 w-4" /></Link>}>
    {dashboard.isLoading ? <div className="data-card rounded-2xl p-8 text-sm text-muted-foreground">Initializing governed workspace…</div> : dashboard.error ? <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-sm text-rose-800">{dashboard.error.message}</div> : data ? <>
      <div className="mb-6 flex flex-wrap items-center gap-2 text-xs"><StatusPill value={data.membership.workspaceRole} /><span className="text-muted-foreground">Workspace boundary</span><WajenziId value={data.workspace.wajenziId} /><span className="ml-auto rounded-full bg-slate-100 px-3 py-1.5 font-medium text-slate-600">{data.workspace.name}</span></div>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Master products" value={data.counts.masterProducts} detail="Canonical identity layer" icon={PackageCheck} /><Metric label="Registry records" value={data.counts.workspaceEntities} detail="Scoped workspace entities" icon={Boxes} accent="text-indigo-700" /><Metric label="Active offers" value={data.counts.activeOffers} detail="Commercial records only" icon={Activity} accent="text-sky-700" /><Metric label="Review queue" value={data.counts.reviewRequired} detail="Steward decisions pending" icon={ShieldAlert} accent="text-amber-700" /><Metric label="Active sites" value={data.counts.activeSites} detail="Distance-ready project anchors" icon={MapPin} accent="text-rose-700" /></section>
      <section className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_0.8fr]">
        <div className="data-card rounded-2xl"><div className="flex items-center justify-between border-b soft-divider px-5 py-4"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted-foreground">Stewardship queue</p><h2 className="mt-1 font-display text-xl text-slate-900">Canonicalization decisions</h2></div><Link href="/submissions" className="text-xs font-bold text-teal-700 hover:text-teal-900">Open queue</Link></div><div className="divide-y soft-divider">{data.reviewQueue.length ? data.reviewQueue.map(item => <div key={item.id} className="flex items-center justify-between gap-4 px-5 py-4"><div className="min-w-0"><p className="truncate font-medium text-slate-800">{item.submittedName}</p><p className="mt-1"><WajenziId value={item.wajenziId} /></p></div><StatusPill value={item.status} /></div>) : <p className="px-5 py-10 text-sm text-muted-foreground">No supplier submission requires review.</p>}</div></div>
        <div className="data-card rounded-2xl"><div className="border-b soft-divider px-5 py-4"><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted-foreground">Import & audit trace</p><h2 className="mt-1 font-display text-xl text-slate-900">Recent registry events</h2></div><div className="divide-y soft-divider">{data.audits.slice(0, 5).map(event => <div key={event.id} className="px-5 py-3.5"><div className="flex items-center justify-between gap-2"><p className="font-mono-data text-[11px] text-teal-800">{event.eventType}</p><span className="text-[11px] text-muted-foreground">{new Date(event.occurredAt).toLocaleDateString()}</span></div><p className="mt-1 text-xs leading-5 text-slate-600">{event.rationale}</p></div>)}<Link href="/implementation" className="flex items-center gap-2 px-5 py-4 text-xs font-bold text-teal-700 hover:text-teal-900"><FileClock className="h-3.5 w-3.5" /> See governed implementation path</Link></div></div>
      </section>
      <section className="mt-6 grid gap-4 md:grid-cols-3">{data.imports.map(batch => <div key={batch.id} className="rounded-2xl border border-slate-200 bg-white/65 p-5"><div className="flex items-center justify-between"><StatusPill value={batch.status} /><WajenziId value={batch.wajenziId} /></div><p className="mt-5 font-medium text-slate-800">{batch.sourceSystem}</p><p className="mt-1 text-xs text-muted-foreground">{batch.processedRows.toLocaleString()} processed · {batch.rejectedRows.toLocaleString()} rejected</p></div>)}</section>
    </> : null}
  </WorkspaceFrame>;
}
