import { WorkspaceFrame } from "@/components/WorkspaceFrame";
import { Bot, CheckCircle2, CircleDashed, Database, FileSearch, GitBranch, ShieldCheck } from "lucide-react";

const complete = [
  ["Ontology & ID registry", "Canonical entity types, immutable WAJENZI IDs, relationship semantics, provenance, merge rules, and controlled vocabularies."],
  ["Master catalogue", "The validated 12,663 canonical product roots and 517 variants are loaded with source-row provenance and idempotent import keys."],
  ["Public reference layer", "Kenya administrative, geographic, Gazette, and construction-reference datasets remain versioned reference observations rather than operational truth."],
  ["Operational registry", "Workspace boundaries, suppliers, projects, sites, facilities, commercial offers, observations, evidence, file metadata, and audit events are available."],
  ["Governed AI agents", "The ontology orchestrator, product intelligence, procurement advisor, and evidence-quality agents produce structured workspace-bound proposals, retain run history, and require human approval for consequential actions."],
];
const next = [
  ["Live supplier onboarding", "Invite verified supplier organizations, link membership to their organization, map their catalogue, and review canonical matches."],
  ["Direct large-file ingestion", "Use browser-to-object-storage uploads and background batch processing for large catalogue files; do not send large CSVs as request bodies."],
  ["Project procurement workflow", "Add requirements, RFQs, quotations, purchase orders, delivery and invoice entities after real operational data is available."],
  ["Specialist-agent expansion", "Add document, drawing, BOQ/estimation, supplier intelligence, project-management, logistics, finance, risk, knowledge/RAG, reporting, and notification agents only as their required governed data models and approval paths become operational."],
];

export default function Implementation() {
  return <WorkspaceFrame eyebrow="Build status & governance" title="Implementation map" description="WAJENZI is being built as a governed data system. The workspace exposes what is operational today, what is deliberately constrained, and the next gates before live supplier or transaction data is introduced." demo={false}>
    <section className="grid gap-6 xl:grid-cols-2"><div className="data-card rounded-2xl"><div className="flex items-center gap-2 border-b soft-divider px-5 py-4"><CheckCircle2 className="h-5 w-5 text-emerald-700" /><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted-foreground">Operational now</p><h2 className="font-display text-xl text-slate-900">Foundation capabilities</h2></div></div><div className="divide-y soft-divider">{complete.map(([title, detail]) => <div key={title} className="p-5"><p className="font-medium text-slate-800">{title}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{detail}</p></div>)}</div></div><div className="data-card rounded-2xl"><div className="flex items-center gap-2 border-b soft-divider px-5 py-4"><CircleDashed className="h-5 w-5 text-amber-700" /><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted-foreground">Next gated capabilities</p><h2 className="font-display text-xl text-slate-900">Production integration path</h2></div></div><div className="divide-y soft-divider">{next.map(([title, detail]) => <div key={title} className="p-5"><p className="font-medium text-slate-800">{title}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{detail}</p></div>)}</div></div></section>
    <section className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white/65 p-5"><Database className="h-5 w-5 text-teal-700" /><p className="mt-4 font-display text-xl text-slate-900">Canonical first</p><p className="mt-2 text-sm leading-6 text-muted-foreground">The product registry is the authority. Supplier systems are source systems that attach commercial records and provenance.</p></div><div className="rounded-2xl border border-slate-200 bg-white/65 p-5"><GitBranch className="h-5 w-5 text-teal-700" /><p className="mt-4 font-display text-xl text-slate-900">No silent merging</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Conflicting identities stay reviewable. A canonical product is created only after a deliberate steward decision.</p></div><div className="rounded-2xl border border-slate-200 bg-white/65 p-5"><ShieldCheck className="h-5 w-5 text-teal-700" /><p className="mt-4 font-display text-xl text-slate-900">Evidence before claims</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Procurement results require a location, comparable price, verified availability, freshness policy, and preserved evidence.</p></div></section>
    <section className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white/65 p-5"><Database className="h-5 w-5 text-teal-700" /><p className="mt-4 font-display text-xl text-slate-900">Canonical first</p><p className="mt-2 text-sm leading-6 text-muted-foreground">The product registry is the authority. Supplier systems are source systems that attach commercial records and provenance.</p></div><div className="rounded-2xl border border-slate-200 bg-white/65 p-5"><GitBranch className="h-5 w-5 text-teal-700" /><p className="mt-4 font-display text-xl text-slate-900">No silent merging</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Conflicting identities stay reviewable. A canonical product is created only after a deliberate steward decision.</p></div><div className="rounded-2xl border border-slate-200 bg-white/65 p-5"><ShieldCheck className="h-5 w-5 text-teal-700" /><p className="mt-4 font-display text-xl text-slate-900">Evidence before claims</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Procurement results require a location, comparable price, verified availability, freshness policy, and preserved evidence.</p></div></section>
    <section className="data-card mt-6 rounded-2xl p-6"><div className="flex items-start gap-3"><span className="rounded-xl bg-indigo-50 p-2.5 text-indigo-700"><Bot className="h-5 w-5" /></span><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted-foreground">Agent operating model</p><h2 className="mt-1 font-display text-2xl text-slate-900">Structured work, not autonomous side effects</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">An orchestrator identifies the relevant canonical entities and can route a bounded request to a specialist agent. Specialist agents receive workspace-scoped facts, return schema-validated JSON, preserve evidence references, distinguish facts from inferences, and create a traceable run/proposal record. The current suite does not execute changes, approve suppliers, verify commercial claims, place orders, trigger payments, or communicate externally.</p></div></div><div className="mt-5 grid gap-3 text-sm md:grid-cols-4"><div className="rounded-xl bg-indigo-50 p-4 text-indigo-950"><strong>1. Resolve</strong><br /><span className="text-xs leading-5">Canonical ID, entity type, relationships, and allowed context.</span></div><div className="rounded-xl bg-teal-50 p-4 text-teal-950"><strong>2. Analyse</strong><br /><span className="text-xs leading-5">Structured facts, cautious inference, missing information, and confidence.</span></div><div className="rounded-xl bg-amber-50 p-4 text-amber-950"><strong>3. Propose</strong><br /><span className="text-xs leading-5">A durable, approval-gated proposal with no silent database action.</span></div><div className="rounded-xl bg-slate-100 p-4 text-slate-950"><strong>4. Audit</strong><br /><span className="text-xs leading-5">Run, proposal, steward decision, rationale, and event record remain traceable.</span></div></div></section>
    <section className="mt-6 rounded-2xl border border-teal-900/10 bg-[#20323a] p-6 text-stone-100"><FileSearch className="h-5 w-5 text-teal-300" /><h2 className="mt-4 font-display text-2xl">Read this before live onboarding</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-stone-300">Do not treat the demonstration workspace as real market intelligence. The next controlled release should introduce a small number of real, verified suppliers with written data-use authorization, facilities, source catalogues, commercial terms, price observations, availability evidence, and accountable workspace memberships.</p></section>
  </WorkspaceFrame>;
}
