import { startLogin } from "@/const";
import { ArrowRight, Blocks, Building2, ClipboardCheck, Compass, Menu, Search, ShieldCheck, Sparkles, Store, UsersRound } from "lucide-react";
import { Link } from "wouter";

const roleEntries = [
  { title: "Contractors", detail: "Plan projects, prepare RFQs, compare commercial responses, and request governed approvals.", icon: Building2, route: "/contractor" },
  { title: "Suppliers", detail: "Present products, maintain commercial offers, respond to invited RFQs, and manage authorized orders.", icon: Store, route: "/supplier" },
  { title: "Project teams", detail: "Connect project, product, location, document, and evidence context in one controlled operating flow.", icon: UsersRound, route: "/project-manager" },
];

export default function PublicHome() {
  return <div className="min-h-screen overflow-hidden bg-[#0d2024] text-stone-100">
    <header className="relative z-20 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8">
      <Link href="/" className="flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-teal-300 text-sm font-black text-teal-950 shadow-[0_12px_30px_rgba(73,224,205,.2)]">W</span><span><b className="block text-sm tracking-wide text-white">wajenzi<span className="text-teal-300">.ai</span></b><span className="block text-[9px] font-bold uppercase tracking-[0.19em] text-slate-400">Construction network</span></span></Link>
      <nav className="hidden items-center gap-7 text-sm text-slate-300 md:flex"><Link href="/marketplace" className="transition hover:text-teal-200">Marketplace</Link><a href="#workflows" className="transition hover:text-teal-200">Workflows</a><a href="#roles" className="transition hover:text-teal-200">For your role</a></nav>
      <div className="flex items-center gap-2"><Link href="/marketplace" className="hidden rounded-xl px-3 py-2 text-sm font-semibold text-teal-100 transition hover:bg-white/5 sm:block">Browse products</Link><button onClick={() => startLogin()} className="rounded-xl bg-teal-300 px-4 py-2.5 text-sm font-extrabold text-teal-950 transition hover:bg-teal-200 active:scale-[0.97]">Sign in <ArrowRight className="ml-1 inline h-4 w-4" /></button><Menu className="h-5 w-5 text-slate-300 md:hidden" /></div>
    </header>
    <main>
      <section className="relative mx-auto max-w-7xl px-5 pb-20 pt-12 lg:px-8 lg:pb-28 lg:pt-20">
        <div className="public-grid absolute inset-x-0 top-0 h-full opacity-30" /><div className="public-orb absolute -right-24 top-12 h-96 w-96 rounded-full" /><div className="absolute -left-32 bottom-0 h-72 w-72 rounded-full border border-teal-300/10" />
        <div className="relative grid items-center gap-12 lg:grid-cols-[1.08fr_0.92fr]">
          <div><div className="inline-flex items-center gap-2 rounded-full border border-teal-200/15 bg-teal-200/5 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[0.17em] text-teal-200"><Compass className="h-3.5 w-3.5" /> Construction intelligence, connected</div><h1 className="mt-6 max-w-3xl font-display text-5xl leading-[0.98] text-white sm:text-6xl lg:text-7xl">Build with <span className="text-teal-300">market intelligence.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-slate-300 sm:text-lg">A governed workspace for construction teams to discover canonical products, source through suppliers, run project procurement, and preserve the evidence behind every operational decision.</p>
            <div className="mt-8 rounded-2xl border border-white/10 bg-white/[0.07] p-2 shadow-[0_24px_55px_rgba(0,0,0,.25)] backdrop-blur"><div className="flex flex-col gap-2 sm:flex-row"><div className="flex min-w-0 flex-1 items-center gap-3 px-3"><Search className="h-5 w-5 shrink-0 text-teal-200" /><input aria-label="Describe your construction requirement" className="min-w-0 flex-1 bg-transparent py-3 text-sm text-white placeholder:text-slate-400 focus:outline-none" placeholder="What are you building, sourcing, or planning?" /></div><div className="flex gap-2"><button onClick={() => startLogin()} className="flex-1 rounded-xl bg-teal-300 px-4 py-3 text-sm font-bold text-teal-950 transition hover:bg-teal-200 sm:flex-none">Start a project</button><Link href="/marketplace" className="flex items-center justify-center rounded-xl border border-white/15 px-4 py-3 text-sm font-bold text-white transition hover:bg-white/10">Find products</Link></div></div></div>
            <div className="mt-6 flex flex-wrap gap-x-5 gap-y-3 text-xs text-slate-300"><span className="inline-flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-teal-300" />Canonical product identity</span><span className="inline-flex items-center gap-2"><ClipboardCheck className="h-4 w-4 text-teal-300" />Evidence-aware workflows</span><span className="inline-flex items-center gap-2"><Blocks className="h-4 w-4 text-teal-300" />Role-aware workspaces</span></div>
          </div>
          <div className="relative mx-auto w-full max-w-lg"><div className="absolute -inset-5 rounded-[2.2rem] border border-teal-300/10" /><div className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-[#112b30] p-5 shadow-2xl shadow-black/30"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(94,234,212,.13)_1px,transparent_1px),linear-gradient(90deg,rgba(94,234,212,.13)_1px,transparent_1px)] [background-size:36px_36px]" /><div className="relative"><div className="flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-teal-200">Connected construction graph</p><span className="h-2 w-2 rounded-full bg-teal-300 shadow-[0_0_18px_4px_rgba(94,234,212,.4)]" /></div><div className="mt-8 grid grid-cols-2 gap-3"><div className="rounded-2xl border border-white/10 bg-[#18363a]/90 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Identity</p><p className="mt-2 font-display text-2xl text-white">Products</p><p className="mt-2 text-xs leading-5 text-slate-300">Canonical records remain distinct from supplier commercial terms.</p></div><div className="mt-8 rounded-2xl border border-teal-200/20 bg-teal-300/10 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-teal-100">Commerce</p><p className="mt-2 font-display text-2xl text-white">Suppliers</p><p className="mt-2 text-xs leading-5 text-slate-300">Offer, quote, and fulfilment context stays attributable.</p></div><div className="rounded-2xl border border-white/10 bg-[#18363a]/90 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Delivery</p><p className="mt-2 font-display text-2xl text-white">Projects</p><p className="mt-2 text-xs leading-5 text-slate-300">Every request is tied to an authorized project and a traceable event.</p></div><div className="mt-8 rounded-2xl border border-white/10 bg-[#18363a]/90 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Control</p><p className="mt-2 font-display text-2xl text-white">Evidence</p><p className="mt-2 text-xs leading-5 text-slate-300">Human approvals remain visible at consequential handoffs.</p></div></div></div></div></div>
        </div>
      </section>
      <section id="workflows" className="bg-[#f6f3eb] py-20 text-slate-900"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-2xl"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-teal-700">One connected operating layer</p><h2 className="mt-3 font-display text-4xl leading-tight">From product discovery to governed project procurement.</h2><p className="mt-4 text-sm leading-7 text-slate-600">The marketplace shows the product identity layer first. Authorized workspaces then connect supplier commercial records, project requirements, RFQs, quotation comparison, approvals, and delivery intent without collapsing their provenance.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[{ icon: Search, title: "Discover", text: "Browse the canonical product catalogue before comparing commercial supplier records." }, { icon: Sparkles, title: "Coordinate", text: "Bring project, location, supplier, requirement, and document context into one workflow." }, { icon: ShieldCheck, title: "Govern", text: "Keep immutable IDs, evidence, audit events, and human authority at key transitions." }].map(({ icon: Icon, title, text }, index) => <article key={title} className="rounded-2xl border border-stone-200 bg-white p-6 shadow-[0_16px_38px_rgba(26,36,35,.06)]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-teal-50 text-teal-800"><Icon className="h-5 w-5" /></span><p className="mt-7 text-[10px] font-bold uppercase tracking-[0.15em] text-stone-400">0{index + 1}</p><h3 className="mt-2 font-display text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>
      <section id="roles" className="bg-[#eef6f2] py-20 text-slate-900"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-teal-700">Role-aware by design</p><h2 className="mt-3 font-display text-4xl">A different view, one governed foundation.</h2></div><button onClick={() => startLogin()} className="rounded-xl bg-[#17383d] px-4 py-3 text-sm font-bold text-white transition hover:bg-[#0d272c]">Open your workspace <ArrowRight className="ml-1 inline h-4 w-4" /></button></div><div className="mt-9 grid gap-4 md:grid-cols-3">{roleEntries.map(({ icon: Icon, title, detail, route }) => <Link key={title} href={route} className="group rounded-2xl border border-teal-900/10 bg-white p-6 transition hover:-translate-y-0.5 hover:shadow-lg"><Icon className="h-5 w-5 text-teal-700" /><h3 className="mt-8 font-display text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{detail}</p><span className="mt-6 inline-block text-xs font-bold text-teal-800">Explore role workspace <ArrowRight className="ml-1 inline h-3.5 w-3.5 transition group-hover:translate-x-0.5" /></span></Link>)}</div></div></section>
    </main>
    <footer className="border-t border-white/10 px-5 py-7 text-center text-xs text-slate-400">wajenzi.ai · Canonical identities, commercial terms, evidence, and operational events remain distinct and traceable.</footer>
  </div>;
}
