import { EmptyState, StatusPill, WajenziId, WorkspaceFrame } from "@/components/WorkspaceFrame";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, GitMerge, Plus, ShieldAlert } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function Submissions() {
  const utils = trpc.useUtils();
  const dashboard = trpc.registry.dashboard.useQuery(undefined, { retry: false });
  const [supplierId, setSupplierId] = useState<number | undefined>();
  const [name, setName] = useState("");
  const [sku, setSku] = useState("");
  const submit = trpc.registry.submitSupplierProduct.useMutation({ onSuccess: result => { toast.success(result.outcome === "matched_existing_product" ? "Matched to an existing canonical product." : "Submission held for registry steward review."); setName(""); setSku(""); utils.registry.dashboard.invalidate(); }, onError: error => toast.error(error.message) });
  const resolve = trpc.registry.resolveSupplierSubmission.useMutation({ onSuccess: () => { toast.success("Canonicalization decision recorded."); utils.registry.dashboard.invalidate(); }, onError: error => toast.error(error.message) });
  const suppliers = dashboard.data?.supplierOrganizations || [];
  return <WorkspaceFrame eyebrow="Controlled canonicalization" title="Supplier matching & stewardship" description="Supplier products are retained as source evidence. A high-confidence match can attach commercial data to a canonical product; unresolved cases cannot create canonical products without a steward decision." action={<div className="rounded-xl border border-white/15 bg-white/10 px-3 py-2 text-xs font-medium text-teal-100">No automatic canonical creation</div>}>
    <section className="grid gap-6 xl:grid-cols-[0.85fr_1.15fr]"><div className="data-card rounded-2xl p-5"><div className="flex items-center gap-2"><Plus className="h-4 w-4 text-teal-700" /><h2 className="font-display text-xl text-slate-900">New supplier submission</h2></div><p className="mt-2 text-xs leading-5 text-muted-foreground">This is a governed source record. It will either map to an existing canonical identity or enter a steward review queue.</p><div className="mt-5 space-y-4"><label className="block text-xs font-bold uppercase tracking-[0.12em] text-slate-600">Supplier organization<select value={supplierId ?? ""} onChange={event => setSupplierId(Number(event.target.value) || undefined)} className="mt-2 w-full rounded-xl border bg-white px-3 py-2.5 text-sm font-normal outline-none focus:border-teal-600"><option value="">Choose supplier</option>{suppliers.map(supplier => <option value={supplier.entityId} key={supplier.id}>{supplier.canonicalName}</option>)}</select></label><label className="block text-xs font-bold uppercase tracking-[0.12em] text-slate-600">Submitted product name<input value={name} onChange={event => setName(event.target.value)} className="mt-2 w-full rounded-xl border bg-white px-3 py-2.5 text-sm font-normal outline-none focus:border-teal-600" placeholder="e.g. Cement 42.5R, 50 kg" /></label><label className="block text-xs font-bold uppercase tracking-[0.12em] text-slate-600">Supplier SKU <span className="font-normal normal-case text-muted-foreground">(optional)</span><input value={sku} onChange={event => setSku(event.target.value)} className="mt-2 w-full rounded-xl border bg-white px-3 py-2.5 text-sm font-normal outline-none focus:border-teal-600" placeholder="Supplier reference" /></label><button disabled={!supplierId || name.trim().length < 2 || submit.isPending} onClick={() => supplierId && submit.mutate({ supplierOrganizationEntityId: supplierId, submittedName: name.trim(), supplierSku: sku.trim() || undefined })} className="flex w-full items-center justify-center gap-2 rounded-xl bg-teal-800 px-4 py-3 text-sm font-bold text-white transition hover:bg-teal-900 disabled:cursor-not-allowed disabled:opacity-50 active:scale-[0.97]"><GitMerge className="h-4 w-4" />{submit.isPending ? "Evaluating identity…" : "Submit for canonicalization"}</button></div></div>
      <div className="data-card rounded-2xl"><div className="flex items-center justify-between border-b soft-divider px-5 py-4"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted-foreground">Stewardship queue</p><h2 className="mt-1 font-display text-xl text-slate-900">Match candidates and decisions</h2></div><ShieldAlert className="h-5 w-5 text-amber-700" /></div>{dashboard.isLoading ? <p className="p-8 text-sm text-muted-foreground">Loading review records…</p> : dashboard.data?.reviewQueue.length ? <div className="divide-y soft-divider">{dashboard.data.reviewQueue.map(item => <div key={item.id} className="p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-medium text-slate-800">{item.submittedName}</p><p className="mt-1"><WajenziId value={item.wajenziId} /></p><p className="mt-2 text-xs text-muted-foreground">Supplier SKU: {item.supplierSku || "Not supplied"} · Submitted {new Date(item.submittedAt).toLocaleDateString()}</p></div><StatusPill value={item.status} /></div><div className="mt-4 flex flex-wrap gap-2"><button disabled={resolve.isPending} onClick={() => resolve.mutate({ submissionId: item.id, outcome: "matched_existing_product", rationale: "Steward confirmed the highest-confidence canonical match after reviewing candidate evidence." })} className="rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-800 hover:bg-emerald-100 disabled:opacity-50">Confirm existing match</button><button disabled={resolve.isPending} onClick={() => resolve.mutate({ submissionId: item.id, outcome: "new_canonical_product", canonicalName: item.submittedName, rationale: "Steward approved a new canonical product after reviewed supplier submission." })} className="rounded-lg border border-teal-200 bg-teal-50 px-3 py-2 text-xs font-bold text-teal-800 hover:bg-teal-100 disabled:opacity-50">Approve new canonical product</button><button disabled={resolve.isPending} onClick={() => resolve.mutate({ submissionId: item.id, outcome: "rejected", rationale: "Steward rejected submission pending corrected supplier evidence." })} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-700 hover:bg-slate-50 disabled:opacity-50">Reject / request correction</button></div></div>)}</div> : <EmptyState title="No records awaiting review" detail="New supplier products will appear here only when they cannot be safely attached to an existing canonical product." />}</div></section>
    <section className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><CheckCircle2 className="h-5 w-5 text-emerald-700" /><p className="mt-4 text-sm font-bold text-emerald-950">Exact or high-confidence match</p><p className="mt-1 text-xs leading-5 text-emerald-800">A supplier listing can be attached; a duplicate master product is not created.</p></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><ShieldAlert className="h-5 w-5 text-amber-700" /><p className="mt-4 text-sm font-bold text-amber-950">Conflict or uncertain identity</p><p className="mt-1 text-xs leading-5 text-amber-800">The source record and candidate evidence are preserved for steward review.</p></div><div className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><GitMerge className="h-5 w-5 text-slate-700" /><p className="mt-4 text-sm font-bold text-slate-900">Approved unmatched product</p><p className="mt-1 text-xs leading-5 text-slate-700">Only a recorded steward decision may issue a new immutable canonical product ID.</p></div></section>
  </WorkspaceFrame>;
}
